//! WH_KEYBOARD_LL hook: keystroke counting + visible-character counting.
//! Phase 3 (T010) — basic keystroke counter + event routing.
//! Phase 5 (T028, T031) — visible-character VK filter + IS_PASSWORD_FIELD guard.
//! Phase 6 (T034) — Ctrl+C/V detection (added in Phase 6).
//!
//! # IME handling note
//!
//! WH_KEYBOARD_LL receives REAL VK codes for every keystroke — including keys
//! consumed by an active IME (e.g., pinyin 'c','e','s','h','i').  The focused
//! window receives WM_KEYDOWN(VK_PROCESSKEY) for those, but the LL hook only
//! sees the original VK code.  Therefore `VK_PROCESSKEY` is **never** seen here
//! for Chinese Pinyin IME input; the old check `vk != VK_PROCESSKEY` alone is
//! not sufficient to exclude IME composition keystrokes.
//!
//! The function `is_consumed_by_ime` uses the IMM32 API to detect whether the
//! current keystroke is going to an active IME composition, and suppresses the
//! visible-char count in that case.  IME-committed characters are counted
//! instead by the UIA TextEditTextChanged handler in `ime/mod.rs`.

use std::cell::RefCell;
use std::sync::atomic::Ordering;

use crossbeam_channel::Sender;
use windows::Win32::Foundation::{LPARAM, LRESULT, WPARAM};
use windows::Win32::Globalization::HIMC;
use windows::Win32::UI::Input::Ime::{
    GCS_COMPSTR, ImmGetCompositionStringW, ImmGetContext, ImmGetOpenStatus, ImmReleaseContext,
};
use windows::Win32::UI::Input::KeyboardAndMouse::GetKeyState;
use windows::Win32::UI::WindowsAndMessaging::{
    CallNextHookEx, GetForegroundWindow, SetWindowsHookExW, HHOOK, KBDLLHOOKSTRUCT,
    WH_KEYBOARD_LL, WM_KEYDOWN, WM_SYSKEYDOWN,
};

use crate::state::IS_PASSWORD_FIELD;
use crate::stats::counters::COUNTERS;
use super::InputEvent;

/// VK_PROCESSKEY may appear from some keyboards/IMEs but is never generated by
/// standard Chinese Pinyin IME in WH_KEYBOARD_LL.  Kept as a safety filter.
const VK_PROCESSKEY: u32 = 0xE5;

/// Virtual-key codes for C and V.
const VK_C: u32 = 0x43;
const VK_V: u32 = 0x56;

/// Returns `true` when the given VK + ctrl-state represents a Ctrl+C (copy).
pub(crate) fn is_ctrl_copy(vk: u32, ctrl_down: bool) -> bool {
    ctrl_down && vk == VK_C
}

/// Returns `true` when the given VK + ctrl-state represents a Ctrl+V (paste).
pub(crate) fn is_ctrl_paste(vk: u32, ctrl_down: bool) -> bool {
    ctrl_down && vk == VK_V
}

thread_local! {
    static KEYBOARD_TX: RefCell<Option<Sender<InputEvent>>> = const { RefCell::new(None) };
}

/// Returns `true` for VK codes that represent a single directly-typed visible
/// character (letter, digit, punctuation, space, numpad digit/operator).
///
/// Excluded: function keys, navigation keys, modifier keys (Shift/Ctrl/Alt/Win),
/// VK_PROCESSKEY (IME-consumed keystrokes handled by UIA), and control codes.
pub(crate) fn is_visible_char(vk: u32) -> bool {
    matches!(
        vk,
        0x20           // Space
        | 0x30..=0x39  // 0–9 (top-row digits)
        | 0x41..=0x5A  // A–Z
        | 0x60..=0x69  // Numpad 0–9
        | 0x6A..=0x6F  // Numpad * + - . /
        | 0xBA..=0xC0  // OEM: ; = , - . / `
        | 0xDB..=0xDF  // OEM: [ \ ] '
        | 0xE2         // OEM_102 (intl keyboard extra key)
    )
}

/// Returns `true` if the given VK code is being consumed by an active IME
/// on the current foreground window.
///
/// Two checks are applied:
/// * **Letters A-Z** (0x41–0x5A): skipped whenever `ImmGetOpenStatus` is TRUE,
///   meaning the IME is in conversion/Chinese-input mode.  Every letter typed
///   in this mode goes to the IME as pinyin, even before a composition string
///   appears.
/// * **All other visible-char VKs** (space, digits, OEM punctuation): skipped
///   only when `ImmGetCompositionStringW(GCS_COMPSTR)` returns a positive
///   length, meaning there is an in-progress composition that the key will
///   interact with (e.g., space to select a candidate, digit to select by
///   index).
///
/// If there is no IME context for the foreground window (e.g., the app has no
/// IME or is in direct-input mode), both checks return `false` and the key is
/// counted normally.
///
/// # Safety
/// May only be called from inside a WH_KEYBOARD_LL callback (or equivalent
/// context where calling cross-thread IMM32 functions is acceptable).
fn is_consumed_by_ime(vk: u32) -> bool {
    unsafe {
        let hwnd = GetForegroundWindow();
        if hwnd.0 == 0 {
            return false;
        }
        let himc: HIMC = ImmGetContext(hwnd);
        if himc.0 == 0 {
            return false; // No IME context → direct input
        }

        let consumed = if (0x41..=0x5A).contains(&vk) {
            // Letter key: consumed whenever the IME is open (in Chinese mode).
            ImmGetOpenStatus(himc).as_bool()
        } else {
            // Space / digit / punctuation: consumed only during active composition.
            // Pass buf=None, bufLen=0 to query the length without copying data.
            ImmGetCompositionStringW(himc, GCS_COMPSTR, None, 0) > 0
        };

        let _ = ImmReleaseContext(hwnd, himc);
        consumed
    }
}

/// Store the channel sender in this thread's local storage.
/// Must be called in the hook thread before [`install_keyboard_hook`].
pub(super) fn set_sender(tx: Sender<InputEvent>) {
    KEYBOARD_TX.with(|cell| *cell.borrow_mut() = Some(tx));
}

/// Install the low-level keyboard hook on the calling thread.
/// Returns the hook handle; keep it alive for the duration of the message loop.
pub(super) fn install_keyboard_hook() -> HHOOK {
    unsafe {
        SetWindowsHookExW(WH_KEYBOARD_LL, Some(keyboard_proc), None, 0)
            .expect("Failed to install WH_KEYBOARD_LL hook")
    }
}

unsafe extern "system" fn keyboard_proc(
    code: i32,
    wparam: WPARAM,
    lparam: LPARAM,
) -> LRESULT {
    if code >= 0 {
        let msg = wparam.0 as u32;
        if msg == WM_KEYDOWN || msg == WM_SYSKEYDOWN {
            let info = &*(lparam.0 as *const KBDLLHOOKSTRUCT);
            let vk = info.vkCode;

            // Phase 3: count every key-down as a keystroke.
            COUNTERS.keystrokes.fetch_add(1, Ordering::Relaxed);

            // Phase 6 (T034): detect Ctrl+C / Ctrl+V.
            // GetKeyState high-order bit is set when the key is pressed.
            let ctrl_down = (GetKeyState(0x11) as u16) & 0x8000 != 0; // VK_CONTROL

            // Determine the detailed event type for Phase 7 per-app tracking,
            // and simultaneously update the global counters (Phase 3/5/6).
            let event = if is_ctrl_copy(vk, ctrl_down) {
                COUNTERS.ctrl_c.fetch_add(1, Ordering::Relaxed);
                InputEvent::CtrlCopy
            } else if is_ctrl_paste(vk, ctrl_down) {
                COUNTERS.ctrl_v.fetch_add(1, Ordering::Relaxed);
                // Ctrl+V must NOT increment characters — pasted content is not typed.
                InputEvent::CtrlPaste
            } else if vk != VK_PROCESSKEY
                && is_visible_char(vk)
                && !IS_PASSWORD_FIELD.load(Ordering::Relaxed)
                && !is_consumed_by_ime(vk)
            {
                // Phase 5 (T031): count direct visible characters.
                // `is_consumed_by_ime` excludes pinyin keystrokes (A-Z in IME
                // conversion mode) and candidate-selection keys (space/digits
                // during active composition).  Those characters are counted
                // instead by the UIA TextEditTextChanged handler (ime/mod.rs).
                COUNTERS.characters.fetch_add(1, Ordering::Relaxed);
                InputEvent::VisibleChar
            } else {
                InputEvent::Keystroke
            };

            // Route event for per-app tracking (Phase 7/US5).
            KEYBOARD_TX.with(|cell| {
                if let Some(tx) = cell.borrow().as_ref() {
                    let _ = tx.try_send(event);
                }
            });
        }
    }
    CallNextHookEx(None, code, wparam, lparam)
}

#[cfg(test)]
mod tests {
    use super::{is_visible_char, is_ctrl_copy, is_ctrl_paste};

    // ── T028: visible-character VK filter ───────────────────────────────────

    #[test]
    fn test_letters_are_visible() {
        // A–Z (0x41–0x5A)
        for vk in 0x41u32..=0x5A {
            assert!(is_visible_char(vk), "VK 0x{vk:02X} (letter) should be visible");
        }
    }

    #[test]
    fn test_digits_are_visible() {
        // Top-row 0–9 (0x30–0x39)
        for vk in 0x30u32..=0x39 {
            assert!(is_visible_char(vk), "VK 0x{vk:02X} (digit) should be visible");
        }
        // Numpad 0–9 (0x60–0x69)
        for vk in 0x60u32..=0x69 {
            assert!(is_visible_char(vk), "VK 0x{vk:02X} (numpad digit) should be visible");
        }
    }

    #[test]
    fn test_space_is_visible() {
        assert!(is_visible_char(0x20));
    }

    #[test]
    fn test_oem_punctuation_is_visible() {
        // ; = , - . / `
        for vk in 0xBAu32..=0xC0 {
            assert!(is_visible_char(vk), "VK 0x{vk:02X} (OEM punct) should be visible");
        }
        // [ \ ] '
        for vk in 0xDBu32..=0xDF {
            assert!(is_visible_char(vk), "VK 0x{vk:02X} (OEM bracket/quote) should be visible");
        }
    }

    #[test]
    fn test_function_keys_not_visible() {
        // F1–F12 (0x70–0x7B)
        for vk in 0x70u32..=0x7B {
            assert!(!is_visible_char(vk), "VK 0x{vk:02X} (Fn key) should NOT be visible");
        }
    }

    #[test]
    fn test_navigation_keys_not_visible() {
        let nav_keys: &[u32] = &[
            0x25, // Left
            0x26, // Up
            0x27, // Right
            0x28, // Down
            0x21, // Page Up
            0x22, // Page Down
            0x23, // End
            0x24, // Home
            0x2D, // Insert
            0x2E, // Delete
        ];
        for &vk in nav_keys {
            assert!(!is_visible_char(vk), "VK 0x{vk:02X} (nav) should NOT be visible");
        }
    }

    #[test]
    fn test_escape_not_visible() {
        assert!(!is_visible_char(0x1B)); // Esc
    }

    #[test]
    fn test_vk_processkey_not_visible() {
        // VK_PROCESSKEY (0xE5) — IME-consumed, counted by UIA instead.
        assert!(!is_visible_char(0xE5));
    }

    #[test]
    fn test_modifier_keys_not_visible() {
        let modifiers: &[u32] = &[
            0x10, // Shift
            0x11, // Ctrl
            0x12, // Alt
            0x5B, // LWin
            0x5C, // RWin
        ];
        for &vk in modifiers {
            assert!(!is_visible_char(vk), "VK 0x{vk:02X} (modifier) should NOT be visible");
        }
    }

    // ── T033: Ctrl+C/V detection logic ──────────────────────────────────────

    #[test]
    fn test_is_ctrl_c_detects_ctrl_plus_c() {
        // VK_C = 0x43, ctrl_down = true → should be detected as Ctrl+C
        assert!(is_ctrl_copy(0x43, true));
    }

    #[test]
    fn test_is_ctrl_v_detects_ctrl_plus_v() {
        // VK_V = 0x56, ctrl_down = true → should be detected as Ctrl+V
        assert!(is_ctrl_paste(0x56, true));
    }

    #[test]
    fn test_ctrl_c_without_ctrl_not_triggered() {
        // VK_C without Ctrl held → NOT Ctrl+C
        assert!(!is_ctrl_copy(0x43, false));
    }

    #[test]
    fn test_ctrl_v_without_ctrl_not_triggered() {
        // VK_V without Ctrl held → NOT Ctrl+V
        assert!(!is_ctrl_paste(0x56, false));
    }

    #[test]
    fn test_ctrl_with_other_key_not_copy_or_paste() {
        // Ctrl+X (0x58) is neither copy nor paste
        assert!(!is_ctrl_copy(0x58, true));
        assert!(!is_ctrl_paste(0x58, true));
    }

    #[test]
    fn test_ctrl_a_not_copy_or_paste() {
        // Ctrl+A (Select All, 0x41) must not trigger copy/paste counters
        assert!(!is_ctrl_copy(0x41, true));
        assert!(!is_ctrl_paste(0x41, true));
    }
}
